exp

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,49 +13,49 @@ on:
 
 jobs:
 
-  lint:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        # only use one version for the lint step
-        python-version: [3.9]
-
-    steps:
-
-      - id: checkout-code
-        uses: actions/checkout@v3
-        with:
-          # Do not persist the token during execution of this job.
-          persist-credentials: false
-
-      - id: prepare-python
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - id: dependencies
-        run: |
-          pip install -r requirements.txt
-          pip install -r requirements.dev.txt
-
-      - id: pylint
-        run: make lint
-
-      - id: mypy
-        run: make mypy
-
-      - id: validate-style
-        run: |
-          make fmt
-          if [ $(git diff --name-only --diff-filter=ACMR | wc -l ) != 0 ]; then
-            echo "Reformatting failed! Please run make fmt on your commits and resubmit!" 1>&2;
-            git diff;
-            exit 1;
-          fi
+#  lint:
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        # only use one version for the lint step
+#        python-version: [3.9]
+#
+#    steps:
+#
+#      - id: checkout-code
+#        uses: actions/checkout@v3
+#        with:
+#          # Do not persist the token during execution of this job.
+#          persist-credentials: false
+#
+#      - id: prepare-python
+#        uses: actions/setup-python@v4
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#
+#      - id: dependencies
+#        run: |
+#          pip install -r requirements.txt
+#          pip install -r requirements.dev.txt
+#
+#      - id: pylint
+#        run: make lint
+#
+#      - id: mypy
+#        run: make mypy
+#
+#      - id: validate-style
+#        run: |
+#          make fmt
+#          if [ $(git diff --name-only --diff-filter=ACMR | wc -l ) != 0 ]; then
+#            echo "Reformatting failed! Please run make fmt on your commits and resubmit!" 1>&2;
+#            git diff;
+#            exit 1;
+#          fi
 
   test:
     runs-on: ubuntu-latest
-    needs: lint
+#    needs: lint
     strategy:
       max-parallel: 4
       matrix:
@@ -85,7 +85,13 @@ jobs:
           pip install -e .
 
       - id: unittest
-        run: make coverage PYTEST_TMPDIR=/tmp/${{ matrix.python-version }}
+        run: |
+          make coverage PYTEST_TMPDIR=/tmp/${{ matrix.python-version }}
+          make coverage PYTEST_TMPDIR=/tmp/${{ matrix.python-version }}
+          make coverage PYTEST_TMPDIR=/tmp/${{ matrix.python-version }}
+          make coverage PYTEST_TMPDIR=/tmp/${{ matrix.python-version }}
+          make coverage PYTEST_TMPDIR=/tmp/${{ matrix.python-version }}
+          make coverage PYTEST_TMPDIR=/tmp/${{ matrix.python-version }}
 
       - id: upload-codecov
         # Third-party action pinned to v2.1.0
